# An example zone file that can be used for testing.

name = "example.com."

[[records]]
name = "example.com."
class = "IN"
ttl = 86400
type = "SOA"
origin = "ns.example.com."
mailbox = "user.example.com."
version = 9000
refresh = 7200
retry = 3600
expire = 1209600
minimum = 3600

[[records]]
name = "example.com."
class = "IN"
ttl = 60
type = "A"
addr = "192.158.1.38"

[[records]]
name = "example.com."
class = "IN"
ttl = 60
type = "A"
addr = "102.210.5.22"

[[records]]
name = "sub.example.com."
class = "IN"
ttl = 60
type = "NS"
host = "ns.sub.example.com."
